server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitterclone2
    username: postgres
    password: atuka123
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    mixed: true
