insert into USERS (user_name, password, email) values ('Tobey', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'tdegrey0@vimeo.com');
insert into USERS (user_name, password, email) values ('Reinwald', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'rhardes1@home.pl');
insert into USERS (user_name, password, email) values ('Juieta', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'jlesser2@cnn.com');
insert into USERS (user_name, password, email) values ('Rossie', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'rhuckel3@goo.ne.jp');
insert into USERS (user_name, password, email) values ('Moishe', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'mashburne4@meetup.com');
insert into USERS (user_name, password, email) values ('Clemence', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'cburston5@tamu.edu');
insert into USERS (user_name, password, email) values ('Ameline', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'abispham6@dropbox.com');
insert into USERS (user_name, password, email) values ('Nerty', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'nuvedale7@slashdot.org');
insert into USERS (user_name, password, email) values ('Kenneth', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'kshakesby8@amazonaws.com');
insert into USERS (user_name, password, email) values ('Huey', '$2a$10$GgBwgFne3kIYnF8JogjtFO1GkWxbyb6Q6F8TGa3oE1LW.jyaiz9B6', 'htettersell9@kickstarter.com');
insert into TWEETS (tweet_title, tweet_text, user_id) values ('non ligula pellentesque ultrices phasellus id', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 2);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('luctus et ultrices', 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 3);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('sed ante vivamus tortor duis mattis', 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 4);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('nisl nunc nisl duis bibendum felis sed interdum venenatis', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo', 7);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('sollicitudin ut suscipit a feugiat et', 'sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa', 3);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('laoreet ut rhoncus aliquet pulvinar sed nisl nunc', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla', 3);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('convallis tortor risus dapibus augue', 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', 10);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('pede venenatis non sodales sed tincidunt eu felis', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 1);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('luctus et ultrices', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 1);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('lobortis convallis tortor risus dapibus augue vel accumsan tellus', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 2);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('diam cras pellentesque volutpat dui maecenas', 'varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices', 8);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('justo in hac habitasse', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 9);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('platea dictumst maecenas ut', 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 1);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('non ligula pellentesque ultrices phasellus id sapien in sapien', 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 2);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('phasellus in felis donec semper sapien a libero', 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 9);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('platea dictumst etiam faucibus cursus urna ut tellus nulla', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 6);
insert into TWEETS (tweet_title, tweet_text, user_id) values ('lobortis convallis tortor', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 6);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (1, 3);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (2, 7);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (7, 9);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (2, 4);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (8, 4);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (7, 5);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (5, 1);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (10, 4);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (2, 1);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (7, 4);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (9, 3);
insert into CUSTOMER_FOLLOWING (customer_id, following_id) values (4, 3);
insert into COMMENTS (tweet_id, user_id, comment_text) values (2, 1, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into COMMENTS (tweet_id, user_id, comment_text) values (3, 1, 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus');
insert into COMMENTS (tweet_id, user_id, comment_text) values (7, 1, 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh');
insert into COMMENTS (tweet_id, user_id, comment_text) values (10, 2, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus');
insert into COMMENTS (tweet_id, user_id, comment_text) values (1, 9, 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed');
insert into COMMENTS (tweet_id, user_id, comment_text) values (4, 5, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a');
insert into COMMENTS (tweet_id, user_id, comment_text) values (6, 2, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into COMMENTS (tweet_id, user_id, comment_text) values (4, 1, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque');
insert into COMMENTS (tweet_id, user_id, comment_text) values (2, 5, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam');
insert into COMMENTS (tweet_id, user_id, comment_text) values (10, 6, 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat');
insert into COMMENTS (tweet_id, user_id, comment_text) values (10, 9, 'sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into COMMENTS (tweet_id, user_id, comment_text) values (9, 7, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum');
insert into COMMENTS (tweet_id, user_id, comment_text) values (4, 9, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet');